name = "formkeeper"
compatibility_date = "2026-07-26"
compatibility_flags = ["nodejs_compat"]

vars = { API_KEY = "5f2c8a820891abe1f41467b27f456e38ba377f592b1e28aee83dbb71705b17db", TURNSTILE_SECRET = "", EMAIL_FROM = "formkeeper@successmove000.email", EMAIL_TO = "" }

[[d1_databases]]
binding = "FORMS_DB"
database_name = "formkeeper-db"
database_id = "aac858b7-6b00-4b7d-8075-c6adb36f6441"

[[kv_namespaces]]
binding = "FORMS_KV"
id = "92ffda2d9a884472b58e2f266a532e1e"
